-- ═══════════════════════════════════════════════════════════════════════════
-- 46 — تكامل Whish الفعلي: معرّف رقمي للطلب، وقيد الإيصال تحت قفل السلسلة
--
-- Whish's API addresses a payment by a NUMERIC externalId, so pay_orders
-- gains an identity column. The rest of this migration is the promise the
-- payment page makes, kept in the database:
--
--   pay_book_receipt(order)   turns a PAID order into an official سند قبض in
--                             baladieh_finance, numbered from the same series
--                             the counter uses (settings.sandouk_series,
--                             Q-YYYY-NNN, max+1 floored by the configured
--                             start) under an advisory lock — a number is
--                             never issued twice, whatever two payments do
--                             simultaneously. Idempotent: an order that
--                             already carries its receipt_no returns it.
--   pay_config()              now answers live (enabled AND mode=live) and
--                             test (enabled AND mode=sandbox) — the page
--                             drops its «قريباً» face only on live; sandbox
--                             testing rides pay.html#test without exposing
--                             citizens to a test gateway.
--   pay_my_orders(phone)      «إيصالاتي» — the payer's own paid orders, by
--                             the same phone-norm match التسجيلات use.
--
-- Booked sanad shape: one receipt per payment (the Q number the payer was
-- promised), category = the service's own ledger category when the order has
-- one service, else the generic «جباية ورسوم بلدية»; every service and its
-- amount is spelled out in البيان; payment_method 'whish'; person, property
-- and the Whish reference all carried.
-- ═══════════════════════════════════════════════════════════════════════════

alter table public.pay_orders
  add column if not exists external_id bigint generated by default as identity;
create unique index if not exists pay_orders_external_idx on public.pay_orders(external_id);

-- ── الإيصال — من طلب مدفوع إلى سند قبض مرقّم ────────────────────────────────
create or replace function public.pay_book_receipt(p_order uuid)
returns text language plpgsql security definer
set search_path = public, pg_temp as $fn$
declare
  v_o      public.pay_orders%rowtype;
  v_year   text;
  v_prefix text := 'Q';
  v_start  int  := 0;
  v_cfg    jsonb;
  v_pre    text;
  v_next   int;
  v_no     text;
  v_cat    text;
  v_desc   text;
begin
  select * into v_o from public.pay_orders where id = p_order for update;
  if not found then raise exception 'الطلب غير موجود'; end if;
  if v_o.receipt_no is not null then return v_o.receipt_no; end if;   -- idempotent
  if v_o.status <> 'paid' then raise exception 'لا إيصال لطلب غير مدفوع'; end if;

  -- قفل سلسلة القبض — القاعدة نفسها منذ اليوم الأول: الرقم لا يصدر مرتين
  perform pg_advisory_xact_lock(hashtext('sandouk_series_income'));

  v_year := to_char((now() at time zone 'Asia/Beirut')::date, 'YYYY');
  select value into v_cfg from public.settings where key = 'sandouk_series';
  if v_cfg is not null then
    v_prefix := coalesce(nullif(btrim(coalesce(
                  v_cfg->'income'->'years'->v_year->>'prefix',
                  v_cfg->'income'->>'prefix')), ''), 'Q');
    v_start  := coalesce((v_cfg->'income'->'years'->v_year->>'start')::int, 0);
  end if;
  v_pre := v_prefix || '-' || v_year || '-';

  select coalesce(max((substring(receipt_no from length(v_pre)+1))::int), 0)
    into v_next
    from public.baladieh_finance
   where entry_type = 'income'
     and receipt_no like v_pre || '%'
     and substring(receipt_no from length(v_pre)+1) ~ '^[0-9]+$';
  v_next := greatest(v_next + 1, greatest(v_start, 1));
  v_no := v_pre || lpad(v_next::text, 3, '0');

  select case when jsonb_array_length(v_o.services) = 1
              then v_o.services->0->>'label'
              else 'جباية ورسوم بلدية' end
    into v_cat;
  select 'دفع إلكتروني عبر Whish — '
         || string_agg((s->>'label') || ' ($' || (s->>'amount') || ')', ' + ')
    into v_desc
    from jsonb_array_elements(v_o.services) s;

  insert into public.baladieh_finance
    (entry_date, entry_type, category, description, amount, stamp_value,
     currency, payment_method, person, receipt_no, property_number,
     notes, created_by)
  values
    ((now() at time zone 'Asia/Beirut')::date, 'income', v_cat, v_desc,
     v_o.amount, 0, v_o.currency, 'whish', v_o.payer_name, v_no,
     v_o.property_number,
     'Whish externalId ' || v_o.external_id
       || coalesce(' · ref ' || v_o.whish_ref, ''),
     'whish-pay');

  update public.pay_orders set receipt_no = v_no where id = p_order;
  return v_no;
end;
$fn$;
-- تُستدعى من whish-callback بمفتاح الخدمة فقط — لا anon ولا authenticated
revoke execute on function public.pay_book_receipt(uuid) from public, anon, authenticated;

-- ── pay_config: علما live وtest — لا بيانات اعتماد أبداً ─────────────────────
create or replace function public.pay_config()
returns jsonb language sql stable security definer
set search_path = public, pg_temp as $fn$
  select coalesce((select value from public.settings where key='pay_services'), '{}'::jsonb)
      || (select jsonb_build_object(
            'live', coalesce((value->>'enabled')::boolean, false)
                    and coalesce(value->>'mode','sandbox') = 'live',
            'test', coalesce((value->>'enabled')::boolean, false)
                    and coalesce(value->>'mode','sandbox') = 'sandbox')
            from public.settings where key='pay_whish');
$fn$;

-- ── إيصالاتي — الدافع يرى دفعاته هو، بمطابقة الرقم المعيارية نفسها ──────────
create or replace function public.pay_my_orders(p_phone text)
returns table(created_at timestamptz, amount numeric, currency text,
              services jsonb, property_number text, receipt_no text, status text)
language sql stable security definer
set search_path = public, pg_temp as $fn$
  select o.created_at, o.amount, o.currency, o.services,
         o.property_number, o.receipt_no, o.status
    from public.pay_orders o
   where public.lb_phone_norm(p_phone) <> ''
     and o.phone_norm = public.lb_phone_norm(p_phone)
     and o.status = 'paid'
   order by o.created_at desc
   limit 50;
$fn$;
grant execute on function public.pay_my_orders(text) to anon, authenticated;
