// ═══════════════════════════════════════════════════════════════════════════
// wadi-strings.js — the shared Arabic / English / French dictionary.
//
// This was pasted, byte for byte, into citizen.html, coop.html, news.html,
// phonebook.html and water.html — five identical copies of the same 5,035
// characters. Changing one Arabic word in the help text meant finding and
// editing it in five files and getting all five right. That is how the two
// duplicate logos and the repeated footer link got in.
//
// Load it after i18n.js and before any page script that reads a string.
// ═══════════════════════════════════════════════════════════════════════════
window.__WADI_STRINGS__ = window.__WADI_STRINGS__ || {ar:{},en:{},fr:{}};
(function(){
  var _d = {
    ar: {"wadiMunName": "بلدية وادي الست", "wadiQadaa": "قضاء الشوف", "wadiHomeAria": "العودة للبوابة الرئيسية", "wadiHelpAria": "مساعدة ودليل الاستخدام", "wadiLangAria": "تغيير اللغة", "whTitle": "❓ دليل وادي الست — كيف تعمل المنصّة؟", "whIntro": "مرحباً بك في المنصّة الرقميّة لبلدية وادي الست. هذا الدليل يشرح أهم الميزات في كل صفحة.", "whLangT": "🌐 تغيير اللغة", "whLangD": "اضغط على AR / EN / FR في أعلى الصفحة لتغيير لغة الواجهة. اللغة تُحفظ تلقائياً وتُطبَّق في كل صفحات المنصّة عند زيارتك التالية.", "whNotifT": "🔔 الإشعارات (Push)", "whNotifD": "فعّل الإشعارات لتستلم تحديثات طلبك، تذكير دورة الري، وأخبار البلدية فوراً على هاتفك دون فتح التطبيق. اضغط على زر «تفعيل الإشعارات» في الصفحة المعنية ووافق على الإذن.", "whCurrT": "💵 العملتان: ليرة لبنانيّة (LBP) ودولار أمريكي (USD)", "whCurrD": "تَستخدم التعاونيّة والخدمات المدفوعة الليرة اللبنانيّة (LBP) والدولار الأمريكي (USD). الأسعار قابلة للتحويل بسعر الصرف المُحدَّث من البلديّة.", "whReqT": "📋 بوابة المواطن (الطلبات)", "whReqD": "قدِّم: شكوى، طلب رعاية اجتماعيّة، طلب ترخيص بناء، استفسار، إفادة عقاريّة، أو شكوى ريّ. ستحصل على رقم مرجعيّ لمتابعة طلبك.", "whCoopT": "🛒 التعاونيّة (Coop)", "whCoopD": "سوق إلكترونيّ للمنتجات المحلّيّة. تصفّح المنتجات، أضِفها للسلّة، وأكمل الطلب عبر واتساب مع البائع.", "whDirT": "📒 الدليل (Yellow Pages)", "whDirD": "دليل أرقام أهالي وادي الست. ابحث بالاسم، العائلة، المهنة، أو المنطقة. احفظ جهة الاتصال كـ vCard أو اتّصل بضغطة واحدة.", "whFoot": "للاستفسار أو الإبلاغ عن مشكلة — توجّه لمركز البلديّة أو استخدم بوابة المواطن.", "whClose": "إغلاق"},
    en: {"wadiMunName": "Wadi El Sit Municipality", "wadiQadaa": "Chouf District", "wadiHomeAria": "Back to main gate", "wadiHelpAria": "Help & user guide", "wadiLangAria": "Change language", "whTitle": "❓ Wadi El Sit Guide — How does the platform work?", "whIntro": "Welcome to the digital platform of Wadi El Sit Municipality. This guide explains the main features across all pages.", "whLangT": "🌐 Change language", "whLangD": "Tap AR / EN / FR at the top of any page to change the interface language. Your choice is saved automatically and applied across all pages.", "whNotifT": "🔔 Push notifications", "whNotifD": "Enable notifications to receive request updates, irrigation reminders, and municipality news instantly on your phone.", "whCurrT": "💵 Two currencies: Lebanese Pound (LBP) & US Dollar (USD)", "whCurrD": "The cooperative and paid services use both Lebanese Pound (LBP) and US Dollar (USD). Prices convert at the rate set by the municipality.", "whReqT": "📋 Citizen Portal (requests)", "whReqD": "Submit complaints, welfare requests, building permits, inquiries, attestations, or irrigation complaints. Keep your reference number.", "whCoopT": "🛒 Cooperative (Coop)", "whCoopD": "Online marketplace for local products. Browse, add to cart, and complete the order via WhatsApp directly with the seller.", "whDirT": "📒 Directory (Yellow Pages)", "whDirD": "Directory of Wadi El Sit residents. Search by name, family, profession, or area. Save the contact as a vCard or call with one tap.", "whFoot": "For questions or to report an issue — visit the municipality office or use the Citizen Portal.", "whClose": "Close"},
    fr: {"wadiMunName": "Municipalité de Wadi El Sit", "wadiQadaa": "Caza du Chouf", "wadiHomeAria": "Retour au portail principal", "wadiHelpAria": "Aide & guide d'utilisation", "wadiLangAria": "Changer de langue", "whTitle": "❓ Guide Wadi El Sit — Comment fonctionne la plateforme ?", "whIntro": "Bienvenue sur la plateforme numérique de la Municipalité de Wadi El Sit.", "whLangT": "🌐 Changer de langue", "whLangD": "Appuyez sur AR / EN / FR en haut de la page. Votre choix est sauvegardé automatiquement.", "whNotifT": "🔔 Notifications push", "whNotifD": "Activez les notifications pour recevoir les mises à jour, rappels d'irrigation et actualités sur votre téléphone.", "whCurrT": "💵 Deux monnaies : Livre libanaise (LBP) & Dollar (USD)", "whCurrD": "La coopérative utilise LBP et USD. Les prix sont convertibles au taux fixé par la municipalité.", "whReqT": "📋 Portail citoyen (demandes)", "whReqD": "Soumettez : plaintes, aide sociale, permis, demandes, attestations, ou plaintes d'irrigation. Conservez votre numéro de référence.", "whCoopT": "🛒 Coopérative (Coop)", "whCoopD": "Marché en ligne pour produits locaux. Parcourez, ajoutez au panier, et finalisez via WhatsApp avec le vendeur.", "whDirT": "📒 Annuaire (Yellow Pages)", "whDirD": "Annuaire des habitants. Recherchez par nom, famille, profession ou région. Enregistrez en vCard ou appelez d'un geste.", "whFoot": "Pour toute question ou problème — rendez-vous au bureau de la municipalité ou utilisez le Portail Citoyen.", "whClose": "Fermer"}
  };
  for(var lng in _d){ for(var k in _d[lng]){ window.__WADI_STRINGS__[lng][k] = _d[lng][k]; } }
  if(typeof I18N !== 'undefined' && I18N && typeof I18N.extend === 'function'){
    try{ I18N.extend(_d); }catch(e){ /* swallow */ }
  }
})();
